name: smart_alarm
description: Smart Alarm App

# Versione dell'app (puoi lasciare default)
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.1   # Versione modificata
  shared_preferences: ^2.2.2
  math_expressions: ^2.3.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# Questa è la sezione corretta per gli asset
flutter:
  uses-material-design: true
  # Aggiungi assets se necessario (non obbligatorio)
  assets:
    - assets/
